name: "Upload Artifact to Artifactory"
description: "Uploads a single build artifact to JFrog Artifactory using JFrog CLI."

inputs:
  file:
    description: Path to the file to upload
    required: true
  destination:
    description: Destination path in Artifactory (e.g., repo/path/filename.ext)
    required: true
  artifactory_url:
    description: Base URL of the JFrog Artifactory instance
    required: true
  artifactory_user:
    description: Artifactory username
    required: true
  artifactory_api_key:
    description: Artifactory API key or password
    required: true

runs:
  using: "composite"
  steps:
    - name: Install JFrog CLI
      shell: bash
      run: |
        mkdir -p $HOME/.jfrog
        curl -fL https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/2.53.0/jfrog-cli-linux-amd64/jf -o $HOME/.jfrog/jf
        chmod +x $HOME/.jfrog/jf
        echo "$HOME/.jfrog" >> $GITHUB_PATH

    - name: Configure JFrog CLI
      shell: bash
      run: |
        jf config add artifactory-server \
          --url="${{ inputs.artifactory_url }}" \
          --user="${{ inputs.artifactory_user }}" \
          --password="${{ inputs.artifactory_api_key }}" \
          --interactive=false

    - name: Upload file to Artifactory
      shell: bash
      run: |
        jf rt u "${{ inputs.file }}" "${{ inputs.destination }}" --server-id=artifactory-server
