name: "Upload Artifacts"
description: "Uploads build artifacts to S3 bucket."

inputs:
  path:
    description: Directory containing the files to upload
    required: true
  destination:
    description: Destination path in the target storage
    required: true
  s3_bucket:
    description: S3 bucket name
    required: true

runs:
  using: composite
  steps:
    - name: Run Docker action
      uses: docker://Dockerfile
      env:
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
        AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
